# Generated by Django 3.0.8 on 2020-07-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achei', '0003_historicotransferencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicotransferencias',
            name='compartimentoDe',
        ),
        migrations.RemoveField(
            model_name='historicotransferencias',
            name='compartimentoPara',
        ),
        migrations.RemoveField(
            model_name='historicotransferencias',
            name='objeto',
        ),
    ]
