# Generated by Django 3.0.8 on 2020-07-04 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achei', '0004_auto_20200703_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicotransferencias',
            name='compartimentoDe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compartimentoDe', to='achei.Compartimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicotransferencias',
            name='compartimentoPara',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compartimentoPara', to='achei.Compartimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicotransferencias',
            name='objeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='achei.Objeto'),
            preserve_default=False,
        ),
    ]
